//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonVogue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceView
    {
        public int Id { get; set; }
        public string ClientInfo { get; set; }
        public string EmployeeInfo { get; set; }
        public string Service { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Date { get; set; }
    }
}
